name: sales-aggregator
# extract:
#   type: csv
#   config:
#     path: ./examples/sales.csv
#     delimiter: ","
extract:
  type: json
  config:
    path: ./examples/products.json
transform:
  - type: filter
    expression: "status == 'Completed'"
  - type: aggregate
    group_by: product
    operations:
      total_sales: "sum(amount)"
      total_quantity: "sum(quantity)"
      transactions: "count()"
load:
  # type: sqlite
  # config:
  #   path: ./examples/sales.db
  #   table: sales_summary
  type: csv
  config:
    path: ./examples/output.csv
schedule:
  interval_seconds: 20
  retries: 5
validate:
  - field: amount
    rule: numeric
  - field: status
    rule: "one_of:Completed,Pending,Canceled"
