name: sales-aggregator
extract:
  type: csv
  config:
    path: ./examples/salefsadsas.csv
    delimiter: ","
transform:
  - type: filter
    expression: "status == 'Completed'"
  - type: aggregate
    group_by: product
    operations:
      total_sales: "sum(amount)"
      total_quantity: "sum(quantity)"
      transactions: "count()"
load:
  type: sqlite
  config:
    path: ./examples/sales.db
    table: sales_summary
schedule:
  interval_seconds: 20
  retries: 5
